-- AUTO-GENERATED by tests/spikes/spike_capture_blobs.lua — do not edit.
-- Real MIDI_GetAllEvts blobs + per-event API ground truth (REAPER 7.75/macOS-arm64).
-- Each entry: blob = raw bytes; notes/ccs/texts = the records mm:load
-- currently produces. parseAllEvts(blob) must reproduce them, idx included.

local function unhex(s) return (s:gsub('..', function(h) return string.char(tonumber(h, 16)) end)) end

return {
  {
    name = 'plain',
    blob = unhex('000000000002000000C005000000001003000000B00764000000000003000000E00050000000000002000000D05A000000000003000000A0404D000000000003000000903C60000000000003000000904050F00000000203000000B10B21000000000003000000803C00000000000003000000804000000000000003000000914364F00000000003000000B00700000000000003000000814300000000000203000000903E46780000000203000000803E0000000000010300000090415878000000010300000080410030FD02000003000000B07B00'),
    notes = {
      { idx = 0, evType = 'note', ppq = 0, endppq = 240, chan = 1, pitch = 60, vel = 96 },
      { idx = 1, evType = 'note', ppq = 0, endppq = 240, chan = 1, pitch = 64, vel = 80 },
      { idx = 2, evType = 'note', ppq = 240, endppq = 480, chan = 2, pitch = 67, vel = 100 },
      { idx = 3, evType = 'note', ppq = 480, endppq = 600, chan = 1, pitch = 62, vel = 70, muted = true },
      { idx = 4, evType = 'note', ppq = 600, endppq = 720, chan = 1, pitch = 65, vel = 88 },
    },
    ccs = {
      { idx = 0, ppq = 0, evType = 'pc', chan = 1, val = 5, shape = 'step' },
      { idx = 1, ppq = 0, evType = 'cc', chan = 1, cc = 7, val = 100, shape = 'linear' },
      { idx = 2, ppq = 0, evType = 'pb', chan = 1, val = 2048, shape = 'step' },
      { idx = 3, ppq = 0, evType = 'at', chan = 1, val = 90, shape = 'step' },
      { idx = 4, ppq = 0, evType = 'pa', chan = 1, pitch = 64, vel = 77, shape = 'step' },
      { idx = 5, ppq = 240, evType = 'cc', chan = 2, cc = 11, val = 33, shape = 'step', muted = true },
      { idx = 6, ppq = 480, evType = 'cc', chan = 1, cc = 7, val = 0, shape = 'step' },
    },
    texts = {
    },
  },
  {
    name = 'sidecars',
    blob = unhex('000000000003000000903C60000000000018000000FF0F4E4F5445203020363020637573746F6D2063746D5F4164000000000C000000F07D52444D010007400041F7000000000003000000B007408C0000000003000000803C00000000000003000000903E5A000000000018000000FF0F4E4F5445203020363220637573746F6D2063746D5F423C000000000C000000F07D52444D010007600042F7000000000003000000B00760B40000000003000000803E0020FE02000003000000B07B00'),
    notes = {
      { idx = 0, evType = 'note', ppq = 0, endppq = 240, chan = 1, pitch = 60, vel = 96 },
      { idx = 1, evType = 'note', ppq = 240, endppq = 480, chan = 1, pitch = 62, vel = 90 },
    },
    ccs = {
      { idx = 0, ppq = 100, evType = 'cc', chan = 1, cc = 7, val = 64, shape = 'step' },
      { idx = 1, ppq = 300, evType = 'cc', chan = 1, cc = 7, val = 96, shape = 'step' },
    },
    texts = {
      { idx = 0, ppq = 0, eventtype = 15, msg = unhex('4E4F5445203020363020637573746F6D2063746D5F41') },
      { idx = 1, ppq = 100, eventtype = -1, msg = unhex('7D52444D010007400041') },
      { idx = 2, ppq = 240, eventtype = 15, msg = unhex('4E4F5445203020363220637573746F6D2063746D5F42') },
      { idx = 3, ppq = 300, eventtype = -1, msg = unhex('7D52444D010007600042') },
    },
  },
  {
    name = 'bezier_sidecar',
    blob = unhex('00000000000C000000F07D52444D010007400041F7000000005003000000B0074000000000000C000000FF0F4343425A20000000003F000000000003000000903C60000000000018000000FF0F4E4F5445203020363020637573746F6D2063746D5F43F00000000003000000803C00000000000003000000903E5A000000000018000000FF0F4E4F5445203020363220637573746F6D2063746D5F44F00000000003000000B00700000000000003000000803E0020FE02000003000000B07B00'),
    notes = {
      { idx = 0, evType = 'note', ppq = 0, endppq = 240, chan = 1, pitch = 60, vel = 96 },
      { idx = 1, evType = 'note', ppq = 240, endppq = 480, chan = 1, pitch = 62, vel = 90 },
    },
    ccs = {
      { idx = 0, ppq = 0, evType = 'cc', chan = 1, cc = 7, val = 64, shape = 'bezier', tension = 0.5 },
      { idx = 1, ppq = 480, evType = 'cc', chan = 1, cc = 7, val = 0, shape = 'step' },
    },
    texts = {
      { idx = 0, ppq = 0, eventtype = -1, msg = unhex('7D52444D010007400041') },
      { idx = 1, ppq = 0, eventtype = 15, msg = unhex('4E4F5445203020363020637573746F6D2063746D5F43') },
      { idx = 2, ppq = 240, eventtype = 15, msg = unhex('4E4F5445203020363220637573746F6D2063746D5F44') },
    },
  },
}
